# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x05\x46\x65\x63ha\x12\x0b\n\x03\x64ia\x18\x01 \x01(\x05\x12\x0b\n\x03mes\x18\x02 \x01(\x05\x12\x0c\n\x04year\x18\x03 \x01(\x05\"E\n\tSumaFecha\x12\x0b\n\x03\x64ia\x18\x01 \x01(\x05\x12\x0b\n\x03mes\x18\x02 \x01(\x05\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\x10\n\x08num_dias\x18\x04 \x01(\x05\"\x1b\n\x06\x43\x65ntro\x12\x11\n\tdistancia\x18\x01 \x01(\x02\"<\n\x07\x44isparo\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0e\n\x06\x61ngulo\x18\x02 \x01(\x02\x12\x11\n\tvelocidad\x18\x03 \x01(\x02\"\x19\n\x04Tiro\x12\x11\n\tdistancia\x18\x01 \x01(\x02\"*\n\x05Mejor\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x11\n\tdistancia\x18\x02 \x01(\x02\"\x07\n\x05Vacio2\xce\x04\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x38\n\x0esiguienteFecha\x12\x11.helloworld.Fecha\x1a\x11.helloworld.Fecha\"\x00\x12;\n\rsumaDiasFecha\x12\x15.helloworld.SumaFecha\x1a\x11.helloworld.Fecha\"\x00\x12:\n\x0f\x64imeCentroDiana\x12\x11.helloworld.Vacio\x1a\x12.helloworld.Centro\"\x00\x12\x38\n\rdisparaCannon\x12\x13.helloworld.Disparo\x1a\x10.helloworld.Tiro\"\x00\x12\x36\n\x0cmejorDisparo\x12\x11.helloworld.Vacio\x1a\x11.helloworld.Mejor\"\x00\x12\x43\n\rSayHelloAgain\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12K\n\x13SayHelloStreamReply\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x30\x01\x12L\n\x12SayHelloBidiStream\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00(\x01\x30\x01\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_HELLOREQUEST']._serialized_start=32
  _globals['_HELLOREQUEST']._serialized_end=60
  _globals['_HELLOREPLY']._serialized_start=62
  _globals['_HELLOREPLY']._serialized_end=91
  _globals['_FECHA']._serialized_start=93
  _globals['_FECHA']._serialized_end=140
  _globals['_SUMAFECHA']._serialized_start=142
  _globals['_SUMAFECHA']._serialized_end=211
  _globals['_CENTRO']._serialized_start=213
  _globals['_CENTRO']._serialized_end=240
  _globals['_DISPARO']._serialized_start=242
  _globals['_DISPARO']._serialized_end=302
  _globals['_TIRO']._serialized_start=304
  _globals['_TIRO']._serialized_end=329
  _globals['_MEJOR']._serialized_start=331
  _globals['_MEJOR']._serialized_end=373
  _globals['_VACIO']._serialized_start=375
  _globals['_VACIO']._serialized_end=382
  _globals['_GREETER']._serialized_start=385
  _globals['_GREETER']._serialized_end=975
# @@protoc_insertion_point(module_scope)
